version: '2.3'
services:

  connect:
    hostname: connect
    image: rstudio/rstudio-connect-preview:${RSC_VERSION}
    scale: 2
    ports:
      - 3939
    privileged: true
    environment:
      - RSC_LICENSE
      - RSC_HASTE_ENABLED=true
