version: '2.3'
services:

  connect:
    hostname: connect
    image: rstudio/sol-eng-connect:${CONNECT_VERSION}
    scale: 2
    ports:
      - 3939
    privileged: true
    environment:
      - CONNECT_LICENSE
