on:
  push:
    branches:
      - master
      - main
      - ci_refactoring
  pull_request:
    branches:
      - master
      - main

name: integration-tests

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RSC_VERSION: 1.8.6
      RSC_LICENSE: ${{ secrets.RSC_LICENSE }}
    steps:
      - uses: actions/checkout@v2

      - name: Docker Network Creation
        run: docker network create connectapi_default
        
      - name: Docker Compose Up
        run: docker-compose up --remove-orphans

      - name: Docker Compose Down
        run: docker-compose down
