on:
  push:
    branches:
      - master
      - main
      - ci_refactoring
  pull_request:
    branches:
      - master
      - main

name: integration-tests

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RSC_VERSION: 1.8.6
      RSC_LICENSE: ${{ secrets.RSC_LICENSE }}
    steps:
      - uses: actions/checkout@v2

      - name: Make Test
        run: make test
        
      - name: Make Clean
        run: make clean
